class Requests:
    REQUEST_NICK = 'REQUEST_NICK'
    REFRESH_CONNECTIONS_LIST = 'REFRESH_CLIENT_LIST'
    GET_HISTORY = 'GET_HISTORY'

class Types:
    REQUEST = 'REQUEST'
    NICKNAME = 'NICKNAME'
    USER_LIST = 'USER_LIST'
    MESSAGE = 'MESSAGE'
